#!/usr/bin/env ruby
# frozen_string_literal: true

branch = `git symbolic-ref --short HEAD`
tickets = branch.scan(/[a-zA-Z]{2,6}-\d+/)

if tickets.any?
  ticket_string = "[#{tickets.join('][')}]"
  `echo '' >> #{ARGV[0]}`
  `echo #{ticket_string} >> #{ARGV[0]}`
end
